drop table if exists companies CASCADE;

create table if not exists companies(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    budget NUMERIC(15, 2) NOT NULL
);