spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**
        - id: company-service
          uri: http://company-service:8081
          predicates:
            - Path=/companies/**