spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-server
          uri: http://user-server:8082
          predicates:
            - Path=/users/**
        - id: company-server
          uri: http://company-server:8081
          predicates:
            - Path=/companies/**